version = 1

test_patterns = ["*/test/**"]

exclude_patterns = [
    "bindings/_miniball_wrap.html",
    "bindings/_miniball_wrap.cpp"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
