sudo: false
language: python
python:
  #- "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  #- "pypy3"
# command to install dependencies
install:
  - pip install tox-travis
  - pip install coveralls
  - pip install Cython
before_script:
  - python setup.py build_ext --inplace --define CYTHON_TRACE
  - python setup.py sdist bdist_wheel
# command to run tests
script:
  - tox
after_success:
  - coveralls
