sudo: false
language: python
python:
  #- "3.5"
  - "3.6"
  #- "3.7"
  #- "3.8"
  #- "3.9"
  #- "pypy3"
# command to install dependencies
install:
  - pip install tox-travis
  - python setup.py build_ext --inplace
  #- pip install coveralls
# command to run tests
script:
  - tox -vv
#after_success: coveralls
